// <auto-generated />
namespace PessoasCrud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Adiciona_Pessoas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adiciona_Pessoas));
        
        string IMigrationMetadata.Id
        {
            get { return "202109170056521_Adiciona_Pessoas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
